// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1Pyc3iVf-v0_7ibUVq-vVWAZMCqXzfY',
    appId: '1:635170836298:web:39ce21ac06968099057bb3',
    messagingSenderId: '635170836298',
    projectId: 'connect-app-3d947',
    authDomain: 'connect-app-3d947.firebaseapp.com',
    storageBucket: 'connect-app-3d947.appspot.com',
    measurementId: 'G-ETHGVH2Y91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8dvTrRv3vDqJ1o7hGQ-aMgV6Pkwr3aJA',
    appId: '1:635170836298:android:1a570fb6516b3e49057bb3',
    messagingSenderId: '635170836298',
    projectId: 'connect-app-3d947',
    storageBucket: 'connect-app-3d947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhMczrfgj1U6WibNzFBmKfJYTxnmfgZNk',
    appId: '1:635170836298:ios:abc4b9ed546ea47c057bb3',
    messagingSenderId: '635170836298',
    projectId: 'connect-app-3d947',
    storageBucket: 'connect-app-3d947.appspot.com',
    iosBundleId: 'com.example.connectApp',
  );
}
